### ISSUE TITLE
Unclear what aug4_db is

### ISSUE THREAD

**Issue by smalers** [jimbrannon/dwr_aug3_scripts#4]
The README file background provided by Mary is unclear.  It describes 3 programs (aug4, aug4_db, dry) when the compile process only produces 2 (`aug4.exe`, `dry.exe`).  It is not clear what how aug4_db should be handled.   The following shows only a few lines difference between the two programs (the printNotice subroutine was added by me to print the copyright/license notice).  The aug4_db file is not mentioned in any of the makefiles.  It could certainly be added as another program in the makefile.

```
diff aug4.for aug4_db.for
308c308
<      9                  34,
---
>      9                  56,
405d404
<         call printNotice(outcli)
843,878d841
<
< c _________________________________________________________
< c     Write the license/copyright notice to standard output.
< c _________________________________________________________
<       subroutine printNotice(out)
<       implicit none
<       integer out
<       write(out,100)
<  100  format(
<      1'AUG3 MODFLOW Groundwater Model Preprocessor',/
<      1'AUG3 is a part of Colorado''s Decision Support Systems ',
<      +'(CDSS)',/
<      +'Copyright (C) 2016-2018 Colorado Department of Natural ',
<      +'Resources',/
<      +'',/
<      +'AUG3 is free software:  you can redistribute it and/or modify',/
<      +'    it under the terms of the GNU General Public License as '
<      +'published by',/
<      +'    the Free Software Foundation, either version 3 of the '
<      +'License, or',/
<      +'    (at your option) any later version.',/
<      +'',/
<      +'    AUG3 is distributed in the hope that it will be useful,',/
<      +'    but WITHOUT ANY WARRANTY; without even the implied '
<      +'warranty of',/
<      +'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  ',
<      +'See the',/
<      +'    GNU General Public License for more details.',/
<      +'',/
<      +'    You should have received a copy of the GNU General ',
<      +'Public License',/
<      +'    along with AUG3.  If not, see ',
<      +'<https://www.gnu.org/licenses/>.',/
<      +72('_'),//)
<       end
<
1619c1582
<             else if(II.lt.44.and.JJ.gt.65) then
---
>             else if(II.lt.67.and.JJ.gt.46) then
1625c1588
<             else if(II.gt.66.and.JJ.gt.55) then
---
>             else if(II.gt.66.and.JJ.gt.52) then
1638c1601
<             else if(II.lt.72.and.JJ.gt.37) then
---
>             else if(II.lt.74.and.JJ.gt.37) then
1647c1610
<             else if(II.gt.77) then
---
>             else if(II.gt.73) then

```

**Comment by maryhalstead** [comment]
This repository is only for archiving the 4 FORTRAN programs used by the AUG3 Project: aug4, aug4_db, dry and gs3ddriv.  Aug4_db was created by CDWR staff before the GitHub site was operational.  The file was created by getting a copy of the aug4 program and making some minor changes so that the program would work with the designated basin application.  The code was compiled on a CDWR desktop.  Gs3driv is a CDWR modified version of the USGS program MODFLOW and was created and compiled prior to any current CDWR staff being employed.  Therefore, there is no documentation or other files and the GitHub site is used as an archive until changes are needed in the future.
